### ISSUE TITLE
requested sudo password but not run as sudo

### ISSUE THREAD

**Issue by theelous3** [JaKooLit/Ubuntu-Hyprland#11]
Hi. Bit of a noob when it comes to groups etc.

On reviewing readme, under the important section, I see

> Do not run this installer as sudo or as root
> This Installer requires a user with a priviledge to install packages

When attempting to run without using sudo as given in the commands:

```
git clone -b 24.04 --depth 1 https://github.com/JaKooLit/Ubuntu-Hyprland.git ~/Ubuntu-Hyprland-24.04
cd ~/Ubuntu-Hyprland-24.04
chmod +x install.sh
./install.sh
```

I am prompted for sudo password. Can you please explain:

> This Installer requires a user with a priviledge to install packages

I am most used to this meaning to add the user to the sudoers group, but that violates rule 1 - don't run as sudo.

Please advise, thank you.

**Comment by JaKooLit** [comment]
it needs to install some packages thats why it is requesting password and you cant launch hyprland on a root environment

and Id like to remind you that if you have everything on root, its a security risk

thats why I set an initial rule, that if detects that its in root enviroment, it wont proceed
