### ISSUE TITLE
Need help removing Hyprland from Ubuntu 24.10 with possible option to revert all packages installed as well

### ISSUE THREAD

**Issue by foxtbirdy** [JaKooLit/Ubuntu-Hyprland#13]
I want to remove the Hyprland from Ubuntu 24.10 completely. This also includes the packages that were installed using this repository's script.

Is it possible?

**Comment by KukicVidan** [comment]
cat /var/log/apt/history.log
try by tracking or just use time shift since repo clearly says to create one before installing and it does not include uninstall script

**Comment by JaKooLit** [comment]
yes its possible

sudo apt remove <package> -y

as stated above, and on readme, no uninstall script added cause I dont know the packages which is already in you system

I have tried adding few months ago, it just made my system unstable

**Comment by foxtbirdy** [comment]
Currently, time shift is not installed over my system. This Ubuntu OS is still freshly installed so a snap backup is also not created. However, I be using the History logs and attempt to manually remove the files.

I'll update the status of the removal in the future.
Additional solutions are welcomed.

**Comment by foxtbirdy** [comment]
These packages are selected as potential removal. They are not core features of the 24.10 so they shouldn't really brick the system. Since I am using a poor system, performing this in a VM is not possible. 

I have a script ready to go to make apt remove all of these packages one by one. Still, need insight from author if there is really a package that I shouldn't remove so that my system won't break.

Following packages are excluded: Curl, zsh, file-roller, pavucontrol, zsh-common

```
packages=(
    "bison"
    "blueman"
    "brightnessctl"
    "cava"
    "cliphist"
    "cppcheck"
    "doxygen"
    "exo-utils"
    "fastfetch"
    "fonts-font-awesome"
    "fonts-firacode"
    "gawk"
    "grim"
    "golang"
    "hyprcursor-util"
    "hyprland"
    "hyprland-protocols"
    "hyprwayland-scanner"
    "inxi"
    "kitty"
    "libatk-bridge2.0-dev"
    "libatk1.0-dev"
    "libatspi2.0-dev"
    "libasound2-dev"
    "libdatrie-dev"
    "libdbus-1-dev"
    "libdbusmenu-glib-dev"
    "libdbusmenu-gtk3-dev"
    "libepoxy-dev"
    "libffmpegthumbnailer4v5"
    "libgdk-pixbuf-2.0-dev"
    "libgbm-dev"
    "libgjs-dev"
    "libgraphite2-dev"
    "libgtk-3-dev"
    "libgtk-layer-shell-dev"
    "libharfbuzz-cairo0"
    "libharfbuzz-dev"
    "libhyprcursor-dev"
    "libhyprlang-dev"
    "libhyprutils-dev"
    "libjpeg-dev"
    "libjpeg-turbo8-dev"
    "libjpeg8-dev"
    "libjbig-dev"
    "libmagic-dev"
    "libmpdclient-dev"
    "libnl-3-dev"
    "libnghttp2-dev"
    "libnvidia-vaapi-driver"
    "libpipewire-0.3-dev"
    "libpsl-dev"
    "libpulse-dev"
    "libpango1.0-dev"
    "libpango1.0-tools"
    "libsharpyuv-dev"
    "libspa-0.2-dev"
    "libsqlite3-dev"
    "libsystemd-dev"
    "libthai-dev"
    "libtiff-dev"
    "libtiffxx6"
    "libubis86-0"
    "libvulkan-validationlayers"
    "libvulkan-utility-libraries-dev"
    "libwayland-bin"
    "libwayland-dev"
    "libwebp-dev"
    "libwebpdecoder3"
    "libxfce4panel-2.0-4"
    "libxfce4ui-2-0"
    "libxfce4ui-common"
    "libxfce4util-bin"
    "libxfce4util-common"
    "libxfce4util7"
    "libxfce4windowing-0-0"
    "libxfce4windowing-common"
    "libxinerama-dev"
    "libxkbcommon-dev"
    "libxkbcommon-x11-dev"
    "libxcomposite-dev"
    "libxcursor-dev"
    "libxdamage-dev"
    "libxfixes-dev"
    "libxi-dev"
    "libxinerama-dev"
    "libxft-dev"
    "libxrandr-dev"
    "libxtst-dev"
    "libzstd-dev"
    "mousepad"
    "mpv"
    "mpv-mpris"
    "nwg-look"
    "nvtop"
    "playerctl"
    "polkit-kde-agent-1"
    "python3-gi-cairo"
    "python3-mako"
    "python3-pyquery"
    "qt5-style-kvantum"
    "qt5ct"
    "qt6-base-dev"
    "qt6ct"
    "qalculate-gtk"
    "sway-notification-center"
    "swappy"
    "thunar"
    "thunar-archive-plugin"
    "thunar-data"
    "thunar-volman"
    "tumbler"
    "tumbler-common"
    "vulkan-validationlayers"
    "vulkan-utility-libraries-dev"
    "waybar"
    "wayland-protocols"
    "wlogout"
    "xarchiver"
    "xfconf"
    "yad"
    "zplug"
)

```

**Comment by JaKooLit** [comment]
you dont need insight from me since all packages that I have set to install are in the script...

nothing hidden..

as Ive said, one of the reason why I have not an uninstall script is the same reason that I cannot guarantee that system wont break..

**Comment by foxtbirdy** [comment]
Well, the removal script worked. I will work on adding a bit more features to the script and then try to create a new fork and merge the addons.
