### ISSUE TITLE
Wallpaper animation change hangs

### ISSUE THREAD

**Issue by unklebonehead** [JaKooLit/Ubuntu-Hyprland#2]
24.04 branch - When changing wallpaper  on any monitor with super+w the animation freezes and stays. 
Animations work fine during light/dark mode switching.

![image](https://github.com/user-attachments/assets/b126092d-1ea9-447e-a418-6dd1e2def85f)
![image](https://github.com/user-attachments/assets/8d6028df-d500-484e-b4ad-0e4fea1cf92a)

**Comment by unklebonehead** [comment]
I spoke too soon. It is now freezing on the light/dark mode change as well.

**Comment by unklebonehead** [comment]
I found a work around. 
I changed the duration to 1 and seems to work better.

**Comment by ChirayuGupta2003** [comment]
I am facing the same issue. How did you change the duration?

**Comment by JaKooLit** [comment]
> I am facing the same issue. How did you change the duration?

![swappy-20240828-193139](https://github.com/user-attachments/assets/129f8cff-7556-431d-bbd0-1f6212b6d7bf)

**Comment by ChirayuGupta2003** [comment]
> > I am facing the same issue. How did you change the duration?
> 
> ![swappy-20240828-193139](https://private-user-images.githubusercontent.com/85185940/362245195-129f8cff-7556-431d-bbd0-1f6212b6d7bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NDIwNTAsIm5iZiI6MTcyNDg0MTc1MCwicGF0aCI6Ii84NTE4NTk0MC8zNjIyNDUxOTUtMTI5ZjhjZmYtNzU1Ni00MzFkLWJiZDAtMWY2MjEyYjZkN2JmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDEwNDIzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1YjkzMGIyZDc1N2U1ODBmMWYxNTQ3ZDNiZGU4OGQ4OGM2YmJmOWM2ZjliZWQzNTE3ZjFiMzcyY2M1ZGUxNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DWNtMtS8YIcmvKRPxXhXnD5TmanrC8xgP1QAK6p36RE)

That worked! But only when I am selecting wallpapers not when selecting random wallpaper through ctrl + shift + w

**Comment by JaKooLit** [comment]
Edit those other scripts.....

you will see those above of WallpaperSelect.sh
