### ISSUE TITLE
[Bug]: rofi Menus & waybar don't change color to match the wallpapers

### ISSUE THREAD

**Issue by Youbey** [JaKooLit/Ubuntu-Hyprland#20]
## Bug Report

I'm in Ubuntu 24.04

### Description

When I change wallpaper, the rofis menus and waybar stay on the same color blue and they don't change to match the wallpaper or theme.

### Screenshots

![image](https://github.com/user-attachments/assets/f7eb4331-e788-4efa-9e1f-7f07e72e8b51)

**Comment by JaKooLit** [comment]
wallust may not be properly installed

cd Ubuntu-Hyprland
edit install-scripts/wallust.sh
remove clear at end

reinstall wallust with
./install-scripts/wallust.sh

DO NOT cd into and ran the wallust.sh within install-scripts directory cause that will fail

**Comment by Youbey** [comment]
Thank you, It's working properly now.
