### ISSUE TITLE
[Bug]: Unable to locate hyprland

### ISSUE THREAD

**Issue by thefoxes86** [JaKooLit/Ubuntu-Hyprland#21]
After the complete installation of all package the scripts that install hyprland fall in error. 

`
[NOTE] Installing hyprland-protocols ...
Reading package lists...Reading package lists...

Building dependency tree...Building dependency tree...
Reading state information...
Reading state information...

E: Unable to locate package hyprland-protocols
[ERROR] hyprland-protocols failed to install :( , please check the install.log. You may need to install manually! Sorry, I have tried :(
[NOTE] Installing hyprwayland-scanner ...
Reading package lists...Reading package lists...

Building dependency tree...Building dependency tree...
Reading state information...
Reading state information...

E: Unable to locate package hyprwayland-scanner
[ERROR] hyprwayland-scanner failed to install :( , please check the install.log. You may need to install manually! Sorry, I have tried :(
[NOTE] Force installing hyprland ...
Reading package lists...Reading package lists...

Building dependency tree...Building dependency tree...
Reading state information...
Reading state information...

E: Unable to locate package hyprland
E: Unable to locate package hyprland
[ERROR] hyprland failed to install. Please check the install.log. You may need to install it manually. Sorry, I have tried :(
`

Someone has similar error and knows how to solve and go ahead ?

**Comment by JaKooLit** [comment]
make sure you download / clone proper branch

im guessing you have ubuntu 24.04 and you cloned the 24.10 branch

**Comment by thefoxes86** [comment]
yes you are right, but the response is always the same. Unable to locate hyprland

**Comment by JaKooLit** [comment]
there is an Install-Logs directory

attach the ones with dates... hyprland.log here
