### ISSUE TITLE
Software and ROS2 files deleted

### ISSUE THREAD

**Issue by rogerioflh** [JaKooLit/Ubuntu-Hyprland#24]
At first, the need for a windows manager arose while working with various terminals using ros2 and I ended up getting to know this one. It's a great windows manager if you're thinking about functionality and, above all, aesthetics, but I'd like to warn those of you who also have ros installed on your machines.
I don't know exactly what happened, but after installing hyprland, the software and its dependencies were uninstalled from my machine, and I got the standard message in the terminal (bashrc) that the path provided couldn't be found precisely because the software had been removed. The only file that remained saved and intact was my ros2_ws folder and its dependencies.
Anyway, this is a warning for anyone who wants to install it and doesn't want to make the same mistake.

**Comment by JaKooLit** [comment]
?

Nothing on the script is uninstalling ros2

is ros2 have wayland support?

**Comment by rogeri0-filho** [comment]
Yes, ROS 2 supports Wayland, but the level of compatibility varies depending on the graphical environment. But this didn't just happen with ROS, my printer drivers and others were also uninstalled. 
In any case, I thought it would be useful to point this out

**Comment by JaKooLit** [comment]
INVALID 

Install script does NOT uninstall anything except the ones stated at

install-scripts/01-hypr-pkgs
which are cargo, mako, rofi, dunst
