### ISSUE TITLE
[Bug]:  When unlocked using a Hyprlock, the system is  non-working

### ISSUE THREAD

**Issue by MatveySDK** [JaKooLit/Ubuntu-Hyprland#26]
### Before submitting report

[24.10]
[Kindly review the log files in Install-Logs directory. Some apps may have not installed properly.]

### Description

When the system goes into standby mode (hyprlock), then when you enter the password. The desktop appears. But only the mouse works

### Steps to Reproduce

1. [The system goes into standby mode(hyprlock)]
2. [unlocking with password]
3. [And the system freezes, except for the mouse cursor]

### Expected Behavior

[After unlocking, the system and windows with programs will work]

### Actual Behavior

[Can only be moved with the mouse]

### show output of `inxi -CGIsSMnr` install package `inxi` if not exist
show output here
```
System:
  Host: ubuntu Kernel: 6.11.0-9-generic arch: x86_64 bits: 64
  Desktop: Hyprland v: 0.41.2 Distro: Ubuntu 24.10 (Oracular Oriole)
Machine:
  Type: Desktop Mobo: Micro-Star model: PRO B760M-A WIFI DDR4 (MS-7D99) v: 1.0
    serial: <superuser required> UEFI: American Megatrends LLC. v: 1.90
    date: 01/10/2024
CPU:
  Info: 6-core model: 12th Gen Intel Core i5-12490F bits: 64 type: MT MCP
    cache: L2: 7.5 MiB
  Speed (MHz): avg: 793 min/max: 800/4600 cores: 1: 800 2: 716 3: 801 4: 800
    5: 800 6: 800 7: 800 8: 800 9: 800 10: 800 11: 800 12: 800
Graphics:
  Device-1: NVIDIA AD106 [GeForce RTX 4060 Ti] driver: nvidia v: 560.35.03
  Display: wayland server: X.Org v: 24.1.2 with: Xwayland v: 24.1.2
    compositor: Hyprland v: 0.41.2 driver: gpu: nvidia,nvidia-nvswitch
    resolution: 1920x1080~144Hz
  API: EGL v: 1.5 drivers: nvidia,swrast
    platforms: gbm,wayland,x11,surfaceless,device
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: nvidia mesa v: 560.35.03
    renderer: NVIDIA GeForce RTX 4060 Ti/PCIe/SSE2
Network:
  Device-1: Intel Raptor Lake-S PCH CNVi WiFi driver: iwlwifi
  IF: wlo1 state: down mac: 4c:5f:70:20:73:62
  Device-2: Realtek RTL8125 2.5GbE driver: r8169
  IF: enp4s0 state: up speed: 100 Mbps duplex: full mac: d8:43:ae:61:48:cb
Sensors:
  System Temperatures: cpu: 38.0 C mobo: N/A
  Fan Speeds (rpm): N/A
Repos:
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/google-chrome.list
    1: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
  Active apt repos in: /etc/apt/sources.list.d/vscode.list
    1: deb [arch=amd64,arm64,armhf] https://packages.microsoft.com/repos/code stable main
  Active apt repos in: /etc/apt/sources.list.d/ubuntu.sources
    1: deb http://ru.archive.ubuntu.com/ubuntu/ oracular oracular-updates oracular-backports main restricted universe multiverse
    2: deb http://security.ubuntu.com/ubuntu/ oracular-security main restricted universe multiverse
Info:
  Memory: total: 32 GiB available: 30.68 GiB used: 2.71 GiB (8.8%)
  Processes: 351 Uptime: 13m Shell: Zsh inxi: 3.3.35


```

### Additional Information

[Is it possible to disable hyprlock? So that the system goes into standby mode for pure Ubuntu?]

**Comment by JaKooLit** [comment]
yes you can disable hyprlock. Its not a necessity

you can edit

~/.config/hypr/hypridle.conf 

and edit according to your preferrence

**Comment by MatveySDK** [comment]
> да, вы можете отключить hyprlock. Это не обязательно
> 
> вы можете редактировать
> 
> ~/.config/hypr/hypridle.conf
> 
> и отредактируйте по своему усмотрению

Is it possible to comment out everything here so that hyprlock does not appear at all?

**Comment by MatveySDK** [comment]
The problem is closed, I dragged the hyprlock file to another temporary folder (backup) and now there is simply no hyprlock

**Comment by jayp76** [comment]
I found that when this happens, i change session with STRG-ALT F2/F3 and Back with ATRG-ALT F1, the session works again
