### ISSUE TITLE
[Bug]: Missing Execution Permissions and Dependency (rofi) Causes Installation Errors

### ISSUE THREAD

**Issue by SAHILGAWLI** [JaKooLit/Ubuntu-Hyprland#30]
### Before submitting report

- **Ubuntu Version:** Ubuntu 24.04 LTS  
- **Logs Reviewed:** Yes, reviewed logs in the `Install-Logs` directory.  

### Description

The Waybar layout window was not changing when executing shortcuts. Upon investigating, I found the `.sh` file required manual execution permissions. Additionally, an error occurred stating `rofi` was not found. Installing `rofi` via pip resolved the issue.  

### Steps to Reproduce

1. Execute the shortcut for changing the Waybar layout window.  
2. Observe no action takes place.  
3. Manually navigate to the `~/.config/hypr` directory.  
4. Try running the `.sh` file and encounter a `rofi not found` error.  
5. Install `rofi` using `pip install rofi`.  
6. Retry, and observe the issue is resolved.  

### Expected Behavior

Executing the shortcut for Waybar layout change should open the Waybar theme changer without requiring manual chmod or installing `rofi`.  

### Actual Behavior

The shortcut failed to execute. Manual chmod of `.sh` files and installation of `rofi` were required to resolve the issue.  

### Screenshots

*No screenshots available.*  

### Additional Information

This bug may occur due to missing dependencies or improper permissions for the `.sh` file. The documentation should mention these prerequisites to prevent similar issues.

**Comment by SAHILGAWLI** [comment]
Dear Maintainer,

I’ve identified an issue with the Waybar layout changer and proposed updates to the documentation:

- Add a note to ensure .sh files have proper execution permissions.
- Specify that rofi is a required dependency and must be installed.

Please review my pull request for these changes to ensure clarity for future users.

**Comment by JaKooLit** [comment]
you need rofi-wayland and not rofi

**Comment by SAHILGAWLI** [comment]
wayland dependency is already satisfied
