### ISSUE TITLE
[Bug]: Installation failed  ^[[33m[NOTE]^[(B^[[m Missing packages logged 

### ISSUE THREAD

**Issue by PrabhaAnde** [JaKooLit/Ubuntu-Hyprland#31]
[install-21-160529_hyprland.log](https://github.com/user-attachments/files/17852354/install-21-160529_hyprland.log)
[install-21-160531_hyprlock.log](https://github.com/user-attachments/files/17852355/install-21-160531_hyprlock.log)
[install-21-160533_hypridle.log](https://github.com/user-attachments/files/17852356/install-21-160533_hypridle.log)
## Installation failed.

I 've followed your steps given in youtube https://www.youtube.com/watch?v=6G6W4Py5E34

Error in log file is
```
hyprland
hypridle
hyprlock
^[[33m[NOTE]^[(B^[[m Missing packages logged at Thu Nov 21 04:33:55 PM EST 2024
```

OS details are ::

```
PRETTY_NAME="Ubuntu 24.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.1 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian

```
[00_CHECK-21-161026_installed.log](https://github.com/user-attachments/files/17852336/00_CHECK-21-161026_installed.log)

Could you please help fixing it

**Comment by JaKooLit** [comment]
I think you downloaded the wrong branch

since you have 24.04.1

you need to clone the 24.04 branch

**Comment by PrabhaAnde** [comment]
Great, Thanks for info, I have tried the 24.04 version. And it worked. Do you know how to remove the other version 24.10 that i have tried. That seem to have created and downloaded huge amount libraries.
