### ISSUE TITLE
[Bug]: VSCode/Idea doesn't launch in the Hyprland - Ubuntu 24.04

### ISSUE THREAD

**Issue by PrabhaAnde** [JaKooLit/Ubuntu-Hyprland#32]
## Bug Report

when i clicked either on  Visual Studio code icon or when i typed code . on kitty terminal. The visual studio code doesnt open. 

Could you please help fixing it?

Another one is, Jetbrains IDEA. It does open, but a lot of notifications flooding means thousands of them saying compilation errors in notifications continuously. 

BTW, that happens only with hyprland. Regular Ubuntu works with no issues.

Could you please help solving both of them. Thanks , much appreciated.

**Comment by acridsoul** [comment]
1. What steps did you take to troubleshoot the issue first?

**Comment by alexismarie8314** [comment]
I had the same issue on ubuntu 24.04.2 LTS, still not working for me. I have tried to uninstall and reinstall vscode from the snap app store, reboot the machine and still unable to open vscode. 

I can open vscode without uninstall it by opening the app store and search vscode and click on open. 
But it is impossible to open it directly neither by using the terminal with the command `code`, nor by using `super + d` and clicking on the application.

**Comment by JaKooLit** [comment]
> I had the same issue on ubuntu 24.04.2 LTS, still not working for me. I have tried to uninstall and reinstall vscode from the snap app store, reboot the machine and still unable to open vscode.
> 
> I can open vscode without uninstall it by opening the app store and search vscode and click on open. But it is impossible to open it directly neither by using the terminal with the command `code`, nor by using `super + d` and clicking on the application.

after you have opened vscode, disable gpu acceleration

1. Open command pallete (Ctrl + Shift + P)
2. Enter "Preferences: Configure Runtime Arguments"
3. Add config: "disable-hardware-acceleration": true
4. Restart VS Code

**Comment by alexismarie8314** [comment]
I applied the modifications but it is still not fixing the issue, neither by using `super +d` nor by using `code` in the terminal.
It is only working by using the application store.

In doubt, I restarted my system, but it is still not working.
