### ISSUE TITLE
[Feature Request]: add support for `Ubuntu 25.04`

### ISSUE THREAD

**Issue by hemangjoshi37a** [JaKooLit/Ubuntu-Hyprland#36]
Please add support for `Ubuntu 25.04 Ubuntu Plucky Puffin`

**Comment by hemangjoshi37a** [comment]
Will the Ubuntu 24.10  setup script work with my 25.04 Ubuntu ?

**Comment by JaKooLit** [comment]
done

https://github.com/JaKooLit/Ubuntu-Hyprland/tree/25.04


Note this is still in Alpha Stage. I will edit as required
