### ISSUE TITLE
[Bug]: Won't install Hyprlock and Hypridle

### ISSUE THREAD

**Issue by RAVEYUS** [JaKooLit/Ubuntu-Hyprland#6]
## Bug Report

Ubuntu: 24.04.1 

### Description
Got this at the end of the script:
"The following local packages are missing from /usr/local/bin and will be logged. 
hypridle is not installed. can't find it in /usr/local/bin/
hyprlock is not installed. can't find it in /usr/local/bin/"

### Steps to Reproduce

1. Just run the script

### Actual Behavior

These were not installed for some reason

**Comment by woquchonglang** [comment]
may be you should install [hypandlang](https://hyprland.org/hyprlang/) manually because I also got this error

**Comment by JaKooLit** [comment]
inside Ubuntu-Hyprland/Install-Logs

can you provide 

xxxxxx-hyprlock / hprlock2.log & hypridle hypridle2.log

xxxxx being date and time..

just all the files that has hypridle and hyprlock 

thanks

**Comment by woquchonglang** [comment]
![Screenshot from 2024-09-19 13-17-36](https://github.com/user-attachments/assets/f608c842-f7c3-41b9-bcc5-9a7de562becb)

**Comment by JaKooLit** [comment]
Thanks for providing the whole log..

as far as I could see, there are even no hyprlant and hyprcursor in the logs

it should build after ags

anyway, I added sleep function after ags build.

This should not skip hyprlang and hyprcursor


to OP, do the following

CD Ubuntu-Hyprland
./install-scripts/hyprlang.sh

./install-scripts/hyprcursor.sh

./install-scripts/hyprland.sh

./install-scripts/hypridle.sh

./install-scripts/hyprlock.sh



OR


after CD into Ubuntu-Hyprland
git stash && git pull

./install.sh

**Comment by RAVEYUS** [comment]
Got it working, Thanks @JaKooLit

**Comment by woquchonglang** [comment]
yeah, when I checkout the branch into 24.04, I also finish the install.sh
