### ISSUE TITLE
[Bug]: Cannot change to other dm to switch to X.org session

### ISSUE THREAD

**Issue by tonyho** [JaKooLit/Ubuntu-Hyprland#7]
### Before submitting report

Purpose

I used the hyperland from this project for months, right now I have to run some program in X.org session, so I try to switch to other X session after install the xubuntu and cinnamon session.

InFo:

Ubuntu 24.04.1

6.8.0-44-generic #44-Ubuntu SMP PREEMPT_DYNAMIC Tue Aug 13 13:35:26 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Description

I want to switch to other X.org based session, for example cinnamon/XFCE, so I use the `sudo dpkg-reconfigure gdm3 ` to switch to other dm, for example the lightdm or xddm or sddm, but it seems only the black screen is there after rebooting.

So, I tried to uncomment the following line in the file `/etc/gdm3/custom.conf` to enable the X.org sessions on gdm login selection, but it still not working :

```
[daemon]
# Uncomment the line below to force the login screen to use Xorg
#WaylandEnable=false
```

### Expected Behavior

I can switch the X.org session from or to hyperland wayland from each other.

**Comment by JaKooLit** [comment]
why do you have to that? 

why dont you just log out and on gdm login manager choose whichever DE you want?

**Comment by JaKooLit** [comment]
![Screenshot_20240926_102430_Samsung Internet](https://github.com/user-attachments/assets/6b4dd8cf-a110-4d85-8c83-e52e2f27ded9)

**Comment by tonyho** [comment]
> why do you have to that?↳
> 
> why dont you just log out and on gdm login manager choose whichever DE you want?↳

Because no X.org session shows in my gdm3 login screen, I guess something has been changed after the hyprland is installed:



![Login](https://github.com/user-attachments/assets/649859a2-c49e-4e55-aaa0-20b5274ca55b)

**Comment by JaKooLit** [comment]
definitely NOT. the script dont change anything on that log in manager unless you opted for sddm

**Comment by tonyho** [comment]
Thanks, now I resolved it by installing the xubuntu-desktop-minimal.
