### ISSUE TITLE
[Bug]: 24.10 Repo missing files and not installing dependencies

### ISSUE THREAD

**Issue by klabacher** [JaKooLit/Ubuntu-Hyprland#8]
### Before submitting report

OS: Ubuntu 24.04.1 LTS x86_64 
Kernel: 6.8.0-45-generic

### Description

Failing on installing, after debuging, some dependencies missing

### Steps to Reproduce

./install.sh 

### Expected Behavior

Everything go fine!

### Actual Behavior

Dependencies not installed:

hyprland
hyprlock

### show output of `inxi -CGIsSMnr` install package `inxi` if not exist
show output here
```
System:
  Host: BattleStation Kernel: 6.8.0-45-generic arch: x86_64 bits: 64
  Desktop: GNOME v: 46.0 Distro: Ubuntu 24.04.1 LTS (Noble Numbat)
Machine:
  Type: Desktop Mobo: ASUSTeK model: TUF H310M-PLUS GAMING/BR v: Rev X.0x
    serial: <superuser required> UEFI: American Megatrends v: 3202
    date: 07/10/2021
CPU:
  Info: 6-core model: Intel Core i5-9400F bits: 64 type: MCP cache:
    L2: 1.5 MiB
  Speed (MHz): avg: 3900 min/max: 800/4100 cores: 1: 3900 2: 3900 3: 3900
    4: 3900 5: 3900 6: 3900
Graphics:
  Device-1: NVIDIA TU116 [GeForce GTX 1650 SUPER] driver: nvidia v: 550.107.02
  Display: x11 server: X.Org v: 21.1.11 with: Xwayland v: 23.2.6 driver: X:
    loaded: nvidia unloaded: fbdev,modesetting,nouveau,vesa
    gpu: nvidia,nvidia-nvswitch resolution: 1: 1920x1080~60Hz 2: 1360x768~60Hz
  API: EGL v: 1.5 drivers: nvidia,swrast
    platforms: gbm,x11,surfaceless,device
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: nvidia mesa v: 550.107.02
    renderer: NVIDIA GeForce GTX 1650 SUPER/PCIe/SSE2
Network:
  Device-1: Intel Ethernet I219-V driver: e1000e
  IF: eno1 state: up speed: 1000 Mbps duplex: full mac: 3c:7c:3f:7a:a1:d8
Sensors:
  System Temperatures: cpu: 88.0 C mobo: N/A gpu: nvidia temp: 42 C
  Fan Speeds (rpm): N/A gpu: nvidia fan: 29%
Repos:
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/ubuntu.sources
    1: deb http://archive.ubuntu.com/ubuntu/ noble noble-updates noble-backports main restricted universe multiverse
    2: deb http://security.ubuntu.com/ubuntu/ noble-security main restricted universe multiverse
Info:
  Memory: total: 16 GiB available: 15.54 GiB used: 3.83 GiB (24.7%)
  Processes: 290 Uptime: 1h 0m Shell: Bash inxi: 3.3.34


```

### Additional Information
Additional logs files attached
[install-26-122011_input.log](https://github.com/user-attachments/files/17151155/install-26-122011_input.log)
[install-26-122004_hypridle2.log](https://github.com/user-attachments/files/17151157/install-26-122004_hypridle2.log)
[install-26-122004_hypridle.log](https://github.com/user-attachments/files/17151158/install-26-122004_hypridle.log)
[install-26-122001_hyprlock.log](https://github.com/user-attachments/files/17151159/install-26-122001_hyprlock.log)
[install-26-121819_rofi_wayland2.log](https://github.com/user-attachments/files/17151160/install-26-121819_rofi_wayland2.log)
[install-26-121819_rofi_wayland.log](https://github.com/user-attachments/files/17151161/install-26-121819_rofi_wayland.log)
[install-26-121811_zsh.log](https://github.com/user-attachments/files/17151163/install-26-121811_zsh.log)
[install-26-121803_xdph.log](https://github.com/user-attachments/files/17151164/install-26-121803_xdph.log)
[install-26-121740_themes.log](https://github.com/user-attachments/files/17151165/install-26-121740_themes.log)
[install-26-121720_nvidia.log](https://github.com/user-attachments/files/17151166/install-26-121720_nvidia.log)
[install-26-121710_hypridle2.log](https://github.com/user-attachments/files/17151167/install-26-121710_hypridle2.log)
[install-26-121710_hypridle.log](https://github.com/user-attachments/files/17151168/install-26-121710_hypridle.log)
[install-26-121708_hyprlock.log](https://github.com/user-attachments/files/17151170/install-26-121708_hyprlock.log)
[install-26-121707_hyprland.log](https://github.com/user-attachments/files/17151171/install-26-121707_hyprland.log)
[install-26-121636_ags2.log](https://github.com/user-attachments/files/17151172/install-26-121636_ags2.log)
[install-26-121636_ags.log](https://github.com/user-attachments/files/17151173/install-26-121636_ags.log)
[install-26-121501_rofi_wayland2.log](https://github.com/user-attachments/files/17151174/install-26-121501_rofi_wayland2.log)
[install-26-121501_rofi_wayland.log](https://github.com/user-attachments/files/17151175/install-26-121501_rofi_wayland.log)
[install-26-121457_swww2.log](https://github.com/user-attachments/files/17151176/install-26-121457_swww2.log)
[install-26-121457_swww.log](https://github.com/user-attachments/files/17151177/install-26-121457_swww.log)
[install-26-121455_fonts.log](https://github.com/user-attachments/files/17151178/install-26-121455_fonts.log)
[install-26-121250_wallust.log](https://github.com/user-attachments/files/17151179/install-26-121250_wallust.log)
[install-26-121246_hypr-pkgs.log](https://github.com/user-attachments/files/17151180/install-26-121246_hypr-pkgs.log)
[install-26-121243_pre-clean-up.log](https://github.com/user-attachments/files/17151182/install-26-121243_pre-clean-up.log)
[install-26-121243_dependencies.log](https://github.com/user-attachments/files/17151183/install-26-121243_dependencies.log)
[install-26-120326_hyprlock.log](https://github.com/user-attachments/files/17151184/install-26-120326_hyprlock.log)
[install-26-120320_hyprland.log](https://github.com/user-attachments/files/17151185/install-26-120320_hyprland.log)
[install-26-120310_hyprland.log](https://github.com/user-attachments/files/17151186/install-26-120310_hyprland.log)
[install-26-120226_input.log](https://github.com/user-attachments/files/17151187/install-26-120226_input.log)
[install-26-120219_hypridle2.log](https://github.com/user-attachments/files/17151188/install-26-120219_hypridle2.log)
[install-26-120219_hypridle.log](https://github.com/user-attachments/files/17151189/install-26-120219_hypridle.log)
[install-26-120217_hyprlock.log](https://github.com/user-attachments/files/17151190/install-26-120217_hyprlock.log)
[install-26-120036_rofi_wayland2.log](https://github.com/user-attachments/files/17151191/install-26-120036_rofi_wayland2.log)
[install-26-120036_rofi_wayland.log](https://github.com/user-attachments/files/17151192/install-26-120036_rofi_wayland.log)
[install-26-120028_xdph.log](https://github.com/user-attachments/files/17151193/install-26-120028_xdph.log)
[install-26-120007_themes.log](https://github.com/user-attachments/files/17151194/install-26-120007_themes.log)
[install-26-115949_nvidia.log](https://github.com/user-attachments/files/17151195/install-26-115949_nvidia.log)
[install-26-115938_hypridle2.log](https://github.com/user-attachments/files/17151196/install-26-115938_hypridle2.log)
[install-26-115938_hypridle.log](https://github.com/user-attachments/files/17151197/install-26-115938_hypridle.log)
[install-26-115936_hyprlock.log](https://github.com/user-attachments/files/17151198/install-26-115936_hyprlock.log)
[install-26-115935_hyprland.log](https://github.com/user-attachments/files/17151199/install-26-115935_hyprland.log)
[install-26-115905_ags2.log](https://github.com/user-attachments/files/17151200/install-26-115905_ags2.log)
[install-26-115905_ags.log](https://github.com/user-attachments/files/17151201/install-26-115905_ags.log)
[install-26-115733_rofi_wayland2.log](https://github.com/user-attachments/files/17151202/install-26-115733_rofi_wayland2.log)
[install-26-115733_rofi_wayland.log](https://github.com/user-attachments/files/17151203/install-26-115733_rofi_wayland.log)
[install-26-115729_swww2.log](https://github.com/user-attachments/files/17151204/install-26-115729_swww2.log)
[install-26-115729_swww.log](https://github.com/user-attachments/files/17151205/install-26-115729_swww.log)
[install-26-115727_fonts.log](https://github.com/user-attachments/files/17151206/install-26-115727_fonts.log)
[install-26-115524_wallust.log](https://github.com/user-attachments/files/17151207/install-26-115524_wallust.log)
[install-26-115520_hypr-pkgs.log](https://github.com/user-attachments/files/17151208/install-26-115520_hypr-pkgs.log)
[install-26-115517_pre-clean-up.log](https://github.com/user-attachments/files/17151210/install-26-115517_pre-clean-up.log)
[install-26-115517_dependencies.log](https://github.com/user-attachments/files/17151211/install-26-115517_dependencies.log)
[install-26-114906_hyprlock.log](https://github.com/user-attachments/files/17151212/install-26-114906_hyprlock.log)
[install-26-114904_hypridle.log](https://github.com/user-attachments/files/17151213/install-26-114904_hypridle.log)
[install-26-114903_hyprland.log](https://github.com/user-attachments/files/17151215/install-26-114903_hyprland.log)
[install-26-114840_dotfiles.log](https://github.com/user-attachments/files/17151216/install-26-114840_dotfiles.log)
[install-26-114739_input.log](https://github.com/user-attachments/files/17151217/install-26-114739_input.log)
[install-26-114737_hypridle.log](https://github.com/user-attachments/files/17151218/install-26-114737_hypridle.log)
[install-26-114735_hyprlock.log](https://github.com/user-attachments/files/17151219/install-26-114735_hyprlock.log)
[install-26-114604_rofi_wayland2.log](https://github.com/user-attachments/files/17151221/install-26-114604_rofi_wayland2.log)
[install-26-114604_rofi_wayland.log](https://github.com/user-attachments/files/17151222/install-26-114604_rofi_wayland.log)
[install-26-114124_zsh.log](https://github.com/user-attachments/files/17151223/install-26-114124_zsh.log)
[install-26-114102_xdph.log](https://github.com/user-attachments/files/17151224/install-26-114102_xdph.log)
[install-26-113938_thunar.log](https://github.com/user-attachments/files/17151225/install-26-113938_thunar.log)
[install-26-113918_themes.log](https://github.com/user-attachments/files/17151226/install-26-113918_themes.log)
[install-26-113845_nvidia.log](https://github.com/user-attachments/files/17151227/install-26-113845_nvidia.log)
[install-26-113831_hypridle.log](https://github.com/user-attachments/files/17151228/install-26-113831_hypridle.log)
[install-26-113822_hyprlock.log](https://github.com/user-attachments/files/17151230/install-26-113822_hyprlock.log)
[install-26-113821_hyprland.log](https://github.com/user-attachments/files/17151231/install-26-113821_hyprland.log)
[install-26-113055_ags2.log](https://github.com/user-attachments/files/17151232/install-26-113055_ags2.log)
[install-26-113055_ags.log](https://github.com/user-attachments/files/17151233/install-26-113055_ags.log)
[install-26-112911_rofi_wayland2.log](https://github.com/user-attachments/files/17151234/install-26-112911_rofi_wayland2.log)
[install-26-112911_rofi_wayland.log](https://github.com/user-attachments/files/17151235/install-26-112911_rofi_wayland.log)
[install-26-112713_swww2.log](https://github.com/user-attachments/files/17151236/install-26-112713_swww2.log)
[install-26-112713_swww.log](https://github.com/user-attachments/files/17151237/install-26-112713_swww.log)
[install-26-112702_fonts.log](https://github.com/user-attachments/files/17151239/install-26-112702_fonts.log)
[install-26-112455_wallust.log](https://github.com/user-attachments/files/17151240/install-26-112455_wallust.log)
[install-26-111934_hypr-pkgs.log](https://github.com/user-attachments/files/17151241/install-26-111934_hypr-pkgs.log)
[install-26-111632_pre-clean-up.log](https://github.com/user-attachments/files/17151242/install-26-111632_pre-clean-up.log)
[install-26-111632_dependencies.log](https://github.com/user-attachments/files/17151243/install-26-111632_dependencies.log)
[00_CHECK-26-122015_installed.log](https://github.com/user-attachments/files/17151244/00_CHECK-26-122015_installed.log)
[00_CHECK-26-120231_installed.log](https://github.com/user-attachments/files/17151245/00_CHECK-26-120231_installed.log)
[00_CHECK-26-114840_installed.log](https://github.com/user-attachments/files/17151247/00_CHECK-26-114840_installed.log)

**Comment by JaKooLit** [comment]
use the 24.04 branch instead since u have 24.04.1 LTS ubuntu

24.10 branch is ONLY for Ubuntu 24.10
